# -------------- Constants --------------
# NOTE: Please do not edit this file some
# of the constants here are important to
# stay unchaged.

# Primary info
PACKAGE = "unlisted"
VERSION = "0.1.3"
AUTHOR = "ramsy0dev"
GITHUB = "https://github.com/ramsy0dev/unlisted"

# Unlisted's banner
BANNER = f"""[bold white]
                 _ _     _           _
     /\\ /\\ _ __ | (_)___| |_ ___  __| |
    / / \\ \\ '_ \\| | / __| __/ _ \\/ _` |
    \\ \\_/ / | | | | \\__ \\ ||  __/ (_| |
     \\___/|_| |_|_|_|___/\\__\\___|\\__,_| Version [italic cyan]{VERSION}[reset]
                    made by [bold white]`ramsy0dev[bold white]`[reset]
"""

def banner() -> None:
    """ Unlisted's banner """
    from rich import print
    
    print(BANNER)

# Saving data template
UNLISTED_VIDEOS_DATA = {
    "package": PACKAGE,
    "version": VERSION,
    "author": AUTHOR,
    "channel_name": None,
    "unlisted_videos_data": [],
    "used_videos_uid": []
}
